name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint pylint-exit pytest pytest-cov -r requirements.txt
    - name: Analysing the code with pylint
      run: |
        pylint --rcfile=pylintrc src/ run_streamlit.py run_flask.py || pylint-exit $?
    - name: Test the code with pytest
      run: |
        pytest test/ --cov=src.backend --cov-report=html
